namespace Enigma.Core.Asymmetric.Pqc;

/// <summary>
/// Selects which representation of a post-quantum private key is stored in a PKCS#8 private-key PEM. All three
/// carry the same key and all three read back as the expanded FIPS encoding; they differ only in size and in what
/// other implementations can do with the file.
/// </summary>
/// <remarks>
/// This choice is only available when the key is generated by the PEM service itself
/// (<c>GenerateKeyPairPem</c>), because the seed exists only at generation time: it cannot be recovered from an
/// expanded FIPS 203/204 private key, so serializing an existing key always writes
/// <see cref="ExpandedKey"/>.
/// </remarks>
public enum MLPrivateKeyPemFormat
{
    /// <summary>
    /// Store only the generation seed — 32 bytes for ML-DSA, 64 for ML-KEM. The default, and by far the smallest:
    /// an ML-DSA-65 private-key PEM is roughly 130 characters (a 54-byte PKCS#8 body) against roughly 5 600 for
    /// <see cref="ExpandedKey"/>. The expanded key is re-derived on read, so nothing is lost.
    /// <para>
    /// This is Enigma.Core's default, not BouncyCastle's, and not what <c>IMLDsaService.GenerateKeyPair</c> /
    /// <c>IMLKemService.GenerateKeyPair</c> hand back — those always return the expanded encoding.
    /// </para>
    /// </summary>
    Seed,

    /// <summary>
    /// Store only the expanded FIPS private key — a 4 060-byte PKCS#8 body for ML-DSA-65, roughly 5 600
    /// characters of PEM. The most interoperable choice: it needs no seed-expansion support from the reader.
    /// </summary>
    ExpandedKey,

    /// <summary>
    /// Store both the seed and the expanded key — a 4 098-byte PKCS#8 body for ML-DSA-65, roughly 5 650
    /// characters of PEM. The largest form; it lets a reader either use the expanded key directly or re-derive it
    /// from the seed and check the two agree.
    /// </summary>
    SeedAndExpandedKey,
}
